=== Jubeki/doctor-olivier-medical-practice/blog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT posts (post*)>
<!ELEMENT post (title, author, content, attachments?)>
<!ATTLIST post published CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT attachments ((images?, links?) | (links?, images?))>
<!ELEMENT links (link*)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link location CDATA #REQUIRED>
<!ELEMENT images (image*)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image location CDATA #REQUIRED>

=== Jubeki/doctor-olivier-medical-practice/blog.xml
<?xml version="1.1" encoding="UTF-8" ?>
<!DOCTYPE posts SYSTEM "blog.dtd">
<posts>

    <post published="2020-11-03">

        <title>Annual Checkups Deliver Value to Women</title>
        <author>Pacific Medical Centers</author>
        <content>
            Women are natural jugglers. With careers or school, spouses, children, and maybe a vacation or hobby, they still run circles around the Cirque de Soleil. As a family medicine physician, I know first-hand that women frequently put others’ needs first and their own health needs second. I encourage women to reconsider the value of regular checkups, screenings and conversations with your primary care physician.

            For starters, screening and regular checkups can save lives. They can help women avoid late detection of many health issues. An easy example is cervical cancer screening. Most cervical cancers are easy to detect with regular screening and, if found early, are highly curable.
            
            I see a two-fold value in women regularly seeing their doctor. First, the doctor will identify areas where their patients can improve their health and will collaborate with them. Secondly, because everyone is different, the doctor can help them implement changes in ways that will be effective and work with their lifestyle and situation.
            
            The changes many women should consider making are in some ways obvious, but they are difficult to do—otherwise, we would already be doing them. I call these therapeutic lifestyle changes. These involve diet and nutrition, exercise, getting adequate sleep, and so forth. They also include minimizing negative behaviors such as smoking, alcohol intake, unhealthy food and stress. For example, it’s important to manage stress in a healthy way, rather than by drinking or eating too much. The primary care doctor can also help patients who are having trouble coping with life’s stressors by arranging for them to get counseling when needed or by identifying if they are having biochemical imbalance issues.
            
            To get a handle on your health, begin with an annual physical. During this appointment, your provider will conduct regular screenings such as for breast cancer, colon cancer, osteoporosis, cardiovascular disease and diabetes. Your provider will also explore your medical history to look for risks based on past medical issues, your psycho-social history and family history.
            
            Of great importance to many women is, of course, contraception and sexual health. Counseling about contraceptives and other aspects of sexual health occurs during annual visits, as well. Younger women can learn about the latest advances in contraceptives, while women in the perimenopausal years may have questions about their real needs for contraceptive management and associated risk factors.
            
            From screenings to getting your questions answered to making lifestyle changes, your basic checkup offers an opportunity to keep your health at its optimum level. Call your doctor’s office today. Ideally, it’s always better to catch health issues early.
        </content>

        <attachments>

            <links>
    
                <link location="#">Make an appointment</link>
                <link location="https://www.pacificmedicalcenters.org/physician-articles/annual-checkups-deliver-value-to-women">Source (Used only for education purposes)</link>
    
            </links>

        </attachments>

    </post>

    <post published="2020-09-26">

        <title>"A huge breath of fresh air"</title>
        <author>Pacific Medical Centers</author>
        <content>
            Over six years and across three military bases on two continents, Sabina Saburova Glaspie—mother of two and a legal assistant for the U.S. Department of Justice—struggled to take in air.

            After jogging, she says, “I would not be able to breathe.” Others noticed as well. Her husband, friends and even strangers would ask, “Is everything okay, while you’re breathing like that?” “This has been bothering me for so many years,” Sabina says. “Nobody listened to me, that it’s a nose issue. Nothing else.”

            Sabina had a sense of what her problem was, but the many doctors she consulted all prescribed the same thing: asthma medications that didn’t help.

            That was until her husband, Brandon Glaspie, transferred to serve as a Staff Sergeant at Joint Base Lewis-McChord. The family opted into the US Family Health Plan (USFHP), a TRICARE Prime managed care option for active-duty military families in the Puget Sound area.

            This allowed the family to visit the medical team at PacMed.

            Sabina started with a virtual consultation, then a visit to PacMed’s Ear, Nose and Throat team (also called otolaryngology). She was nervous at first, due to COVID-19, but “I saw a lady wiping down the elevator button, so that was very, you know, reassuring.”

            Her primary care physician, Dr. Alexander Park, referred her to otolaryngologist Dr. Michael Wolfe, who diagnosed the problem correctly (a crooked septum—a normal genetic variation). He then referred her to surgeon Dr. Michael Lamperti—all in the same office. Sabina calls her care team “Awesome… very upfront and honest.”

            After clearing a COVID-19 test, Sabina’s surgery went smoothly. She had heard that patients bruise up or develop bags under their eyes after similar procedures, but “I didn’t have any of that,” she says. “I had a great experience…. The people around me can’t even tell that I had something.”

            Asked what she would tell other patients, Sabina says, “With COVID, I think a lot of people are scared. I know I was…. It was a big, scary moment for me, going to the hospital and under anesthesia for the first time. But the doctors talked me through it, and I had to have some faith in them. In the end, they actually, you know, trained to do this. I should be able to trust them, and I had a great outcome.”

            Just a few weeks out from surgery, Sabina is still healing up, but she already feels some relief. “It was, literally, such a relief to get that off my shoulders. Somebody believes me—you actually got listened to. That was very helpful that somebody’s actually paying attention to, you know, to my health, with me, and being a little more proactive.”

            Sabina expects even more relief when the swelling goes down. “I can imagine that it would be just a huge breath of fresh air.”
        </content>

        <attachments>

            <images>

                <image location="https://www.pacificmedicalcenters.org/images/uploads/glaspie_vff.jpg">Sabina Saburova Glaspie struggled to breathe for years—until she found USFHP and PacMed</image>

            </images>

            <links>

                <link location="https://www.pacificmedicalcenters.org/about-us/news-press/a-huge-breath-of-fresh-air/">Source (Used only for education purposes)</link>
    
            </links>

        </attachments>

    </post>

    <post published="2020-05-18">

        <title>Coronavirus Advice</title>
        <author>Boroughloch Medical Practice</author>
        <content>
            The Scottish Government provides the following Coronavirus advice:

            - wear a face covering
            - avoid crowded places
            - clean hands and surfaces regularly
            - stay 2m away from other people
            - self-isolate and book a test if you have COVID-19 symptoms
            
            All patients are requested to be aware of what you can and cannot do to suppress the virus by reading (information from the Scottish Government)[https://www.gov.scot/coronavirus-covid-19/] .

            Much useful information is also freely available (from the NHS)[https://www.nhsinform.scot/illnesses-and-conditions/infections-and-poisoning/coronavirus-covid-19], which includes (Test and Protect)[https://www.nhsinform.scot/campaigns/test-and-protect], the national scheme designed to stop the spread.
        </content>

        <attachments>

            <images>

                <image location="https://www.boroughlochmedicalpractice.com/wp-content/uploads/2020/02/480px-2019-nCoV-CDC-23312_without_background.png">Corinavirus Resources</image>

            </images>

            <links>
    
                <link location="https://www.nhsinform.scot/illnesses-and-conditions/infections-and-poisoning/coronavirus-covid-19/coronavirus-covid-19-general-advice">General advice</link>
                <link location="https://www.nhsinform.scot/self-help-guides/self-help-guide-coronavirus-covid-19">Check your symptoms</link>
                <link location="https://www.nhsinform.scot/illnesses-and-conditions/infections-and-poisoning/coronavirus-covid-19/coronavirus-covid-19-physical-distancing">Physical Distancing</link>
                <link location="https://www.boroughlochmedicalpractice.com/coronavirus-advice/">Source (Used only for education purposes)</link>
    
            </links>

        </attachments>

    </post>


</posts>
